- name: "Install zsh (Debian)"
  become: yes
  apt:
    name: "zsh"
    state: "present"
  when: ansible_facts['os_family'] == "Debian"
  
- name: "Install zsh (Archlinux)"
  become: yes
  pacman:
    name: "zsh"
    state: "present"
  when: ansible_facts['os_family'] == "Archlinux"

- name: "Copy zsh env file to home dir"
  copy:
    src: "zsh/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
  with_items:
    - .zshenv

- name: "Create zsh config dir"
  file:
    path: "{{ xdg_config_home }}/zsh"
    state: "directory"

- name: "Create zsh state dir"
  file:
    path: "{{ xdg_state_home }}/zsh"
    state: "directory"

- name: "Copy zsh setting files to config dir"
  copy:
    src: "zsh/{{ item }}"
    dest: "{{ xdg_config_home }}/zsh/{{ item }}"
  with_items:
    - .zshrc

- name: "Change default shell"
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    shell: "/usr/bin/zsh"
