- name: "fzf"
  include_tasks: fzf.yaml

- name: "ghq"
  include_tasks: ghq.yaml

- name: "pyenv"
  include_tasks: pyenv.yaml

- name: "lazygit"
  include_tasks: lazygit.yaml

- name: "nvm"
  include_tasks: nvm.yaml
