- name: "Create XDG dir"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ xdg_cache_home }}"
    - "{{ xdg_config_home }}"
    - "{{ xdg_data_home }}"
    - "{{ xdg_state_home }}"
    - "{{ xdg_bin_home }}"

- name: "Install build tools (Debian)"
  become: yes
  apt:
    name: "build-essential"
    state: "present"
  when: ansible_facts['os_family'] == "Debian"

- name: "Install build tools (Archlinux)"
  become: yes
  pacman:
    name: "base-devel"
    state: "present"
  when: ansible_facts['os_family'] == "Archlinux"

- name: "Install searcher (Debian)"
  become: yes
  apt:
    name: "silversearcher-ag"
    state: "present"
  when: ansible_facts['os_family'] == "Debian"

- name: "Install searcher (Archlinux)"
  become: yes
  pacman:
    name: "the_silver_searcher"
    state: "present"
  when: ansible_facts['os_family'] == "Archlinux"

- name: "Language: Go (1/3)"
  get_url:
    url: "https://go.dev/dl/go1.21.1.linux-amd64.tar.gz"
    dest: "/tmp/go1.21.1.linux-amd64.tar.gz"

- name: "Language: Go (2/3)"
  unarchive:
    src: "/tmp/go1.21.1.linux-amd64.tar.gz"
    dest: "{{ xdg_config_home }}"

- name: "Language: Go (3/3)"
  file:
    src: "{{ xdg_config_home }}/go/bin/go"
    dest: "{{ xdg_bin_home }}/go"
    state: "link"

- name: "Language: Ruby (Debian)"
  become: yes
  apt:
    name: "ruby"
    state: "present"
  when: ansible_facts['os_family'] == "Debian"

- name: "Language: Ruby (Archlinux)"
  become: yes
  pacman:
    name: "ruby"
    state: "present"
  when: ansible_facts['os_family'] == "Archlinux"
